<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >
    <joint name="front_cam_joint" type="fixed">
        <parent link="chassis" />
        <child link="front_cam_link"/>
        <origin xyz="-0.1 0 ${chassis_height/2}" rpy="${pi/2} -${pi/2} -${pi/2}"/>
    </joint>

    <link name="front_cam_link">
        <visual>
            <box size="0.1 0.03 0.02"/>
            <material name="red"/>
        </visual>
        <collision>
            <box size="0.1 0.03 0.02"/>
        </collision>
        <!-- <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder> -->
    </link>

    <gazebo reference="front_cam_link">
        <sensor name="front_camera" type="depth">
          <always_on>1</always_on>
          <visualize>1</visualize>
          <update_rate>30</update_rate>
          <camera>
            <horizontal_fov>1.019272</horizontal_fov>
            <image>
              <width>640</width>
              <height>480</height>
              <format>B8G8R8</format>
            </image>
            <clip>
              <near>0.2</near>
              <far>8</far>
            </clip>
          </camera>
          <plugin name="camera_front" filename="libgazebo_ros_camera.so">
            <ros>
              <namespace>slam_bot</namespace>
            </ros>
            <frame_name>front_cam_link</frame_name>
            <camera_name>front</camera_name>
            <hack_baseline>0.07</hack_baseline>
            <min_depth>0.05</min_depth>
            <max_depth>20.0</max_depth>
          </plugin>
        </sensor>
      </gazebo>

</robot>